version: 2
jobs:
  update_check:
    environment:
      - GOPATH: /home/circleci/go
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/a-know/blog.a-know.me
    steps:
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - run: mkdir -p ~/.config/blogsync
      - run: echo -e "a-know.hateblo.jp\":\"\n  username\":\" a-know\n  password\":\" ${HATEBLO_PASSWARD}\ndefault\":\"\n  local_root\":\" /go/src/github.com/a-know/blog.a-know.me\n" | tr -d \" >> ~/.config/blogsync/config.yaml
      - run: go get github.com/a-know/blogsync
      - run: cd $GOPATH/src/github.com/a-know/blogsync && git checkout change-modify-detection && go install
      - run: cd /go/src/github.com/a-know/blog.a-know.me
      - checkout
      - add-ssh-keys:
          fingerprints:
            - "26:c3:7c:81:84:bf:3c:c7:b6:f3:f8:33:ce:58:5a:db"
      - run:
          name: Blog update check and create PR
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              blogsync pull a-know.hateblo.jp
              git add -N .
              if [ -n "`git status -sb | grep entry`" ]; then
                if [ -z "`git diff | grep Draft`" ]; then
                  BRANCH=blog-update-`date -u "+%Y%m%d"`
                  git config --global user.email ${MY_EMAIL}
                  git config --global user.name ${MY_NAME}
                  git checkout -b ${BRANCH}
                  git add .
                  git commit -m "Automatic blog update `date -u '+%Y-%m-%d'`"
                  if git push ${CIRCLE_REPOSITORY_URL} ${BRANCH}
                  then
                    curl \
                      --header "Accept: application/vnd.github.v3+json" \
                      --data "{\"title\": \"${BRANCH}\", \"head\": \"${CIRCLE_PROJECT_USERNAME}:${BRANCH}\", \"base\":\"${CIRCLE_BRANCH}\" }" \
                      https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls?access_token=${GITHUB_ACCESS_TOKEN}
                  fi
                fi
              fi
            fi

workflows:
  version: 2
  build_and_check:
    jobs:
      - update_check:
          filters:
            branches:
              only: /master/
  nightly:
    triggers:
      - schedule:
          cron: "30 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update_check
